#! /bin/sh

bspc monitor -d 1 2 3 4 5 6 7 8 9 

bspc config border_width         2
bspc config window_gap           3 

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp state=floating follow=on
bspc rule -a Chromium desktop='^1'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a zoom state=floating follow=on

$HOME/.config/bspwm/autostart &
