#!/bin/sh

xinput set-prop "ELAN1200:00 04F3:30BA Touchpad" "libinput Tapping Enabled" 1 &
xfce4-clipman &
numlockx on &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
/usr/bin/lxqt-policykit-agent &
nitrogen --restore &
# nm-applet &
# blueberry-tray &
picom --config /home/daksh/.config/qtile/picom.conf &
dropbox start &
